version: "3.5"
services:
  frontendgenerator:
    build:
      context: ./frontend
    container_name: frontendgenerator_moviecrashhh_admin
    volumes:
      - ./frontend/source:/home/app:rw
    networks:
      - moviecrashhh-admin-network
  backend:
    build:
      context: ./backend
    container_name: backend_moviecrashhh-admin
    env_file:
      - ./backend/environments.env
    volumes:
      - ./backend/source:/home/app:rw
      - ./frontend/source:/home/app/fe:ro
    ports:
      - "9231:9231"
      - "3011:3011"
    networks:
      - moviecrashhh-admin-network
  nginx:
    build:
      context: ./nginx
    container_name: sslnginx_moviecrashhh-admin
    environment:
      - APP_ENVIRONMENT=dev
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - moviecrashhh-admin-network
    ports:
      - "89:89"
networks:
  moviecrashhh-admin-network:
    external: true
